# Generated by Django 4.2 on 2026-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('emp_role', models.CharField(max_length=50, verbose_name='Employee Role')),
                ('emp_loc', models.CharField(max_length=100, verbose_name='Employee Location')),
                ('emp_ph_no', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
